package com.valdifly.domain.testdefinition.valueobject;

public enum AssertionType {
    STATUS_CODE, RESPONSE_BODY, RESPONSE_HEADER,
    ELEMENT_TEXT, ELEMENT_VISIBLE, ELEMENT_ATTRIBUTE,
    PAGE_TITLE, PAGE_URL, RESPONSE_TIME, VARIABLE_VALUE, VISUAL_MATCH
}
