package com.platform.testing.domain.testdefinition.valueobject;

public enum ActionType {
    // ── Web E2E ──
    NAVIGATE_TO, CLICK, DOUBLE_CLICK, TYPE_TEXT, CLEAR_FIELD,
    SELECT_DROPDOWN, HOVER, SCROLL_TO, WAIT_FOR_ELEMENT,
    SWITCH_FRAME, SWITCH_WINDOW, TAKE_SCREENSHOT,
    EXECUTE_JAVASCRIPT, UPLOAD_FILE,
    // ── Mobile E2E ──
    TAP, SWIPE, LONG_PRESS, MOBILE_SCROLL,
    HIDE_KEYBOARD, SET_GEO_LOCATION,
    // ── API ──
    HTTP_REQUEST, SET_HEADER, SET_QUERY_PARAM,
    SET_AUTH, GRAPHQL_QUERY,
    // ── Load ──
    RAMP_UP, CONCURRENT_USERS, THINK_TIME, ASSERT_RESPONSE_TIME,
    // ── Common ──
    SET_VARIABLE, LOG, DELAY, CALL_TEST_CASE
}
