FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY admin-service/build/libs/admin-service-*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-XX:+UseG1GC", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]