FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY report-service/build/libs/report-service-*-fat.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-XX:+UseG1GC", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]